version: '2'

services:
  localproxy:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
